2022/10/06 13:14:07 [error] 31#31: *72 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 99. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttp" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.9:9000", host: "127.0.0.1:8090"
2022/10/06 13:14:07 [error] 31#31: *72 FastCGI sent in stderr: "Exception))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
  
2022/10/06 13:17:16 [error] 31#31: *74 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 99. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.9:9000", host: "127.0.0.1:8090"
2022/10/06 13:17:16 [error] 31#31: *74 FastCGI sent in stderr: "ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '420dee7e-a987-475d-b01a-f78191222d1e',
    'HTTP_ACCEPT' 
2022/10/06 13:18:11 [error] 31#31: *76 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 96. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.9:9000", host: "127.0.0.1:8090"
2022/10/06 13:18:11 [error] 31#31: *76 FastCGI sent in stderr: "ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => 'b78443cc-a410-473a-9763-a7620aa09744',
    'HTTP_ACCEPT' 
2022/10/06 13:19:22 [error] 31#31: *78 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 96. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.9:9000", host: "127.0.0.1:8090"
2022/10/06 13:19:22 [error] 31#31: *78 FastCGI sent in stderr: "\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '2af3a8a6-b259-4149-ab08-de6c9aa55253',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_AU
2022/10/06 13:19:46 [error] 31#31: *80 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 97. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.ph" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.9:9000", host: "127.0.0.1:8090"
2022/10/06 13:19:46 [error] 31#31: *80 FastCGI sent in stderr: "p(724): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '2e7072fc-800e-4cc6-91d6-a90aba842a16',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.
2022/10/06 13:28:34 [error] 31#31: *90 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/api/controllers/shop/ProductController.php on line 73. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /app/api/controllers/shop/ProductController.php on line 73. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#2 /app/api/web/index.php(17): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/v
2022/10/06 13:28:34 [error] 31#31: *90 FastCGI sent in stderr: "in:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_COOKIE' => '_csrf-frontend=8ce70cfd79bdb811f8b95b940734215e02055b7988defcb8f06aabb24f8ddc7ca%3A2%3A%7Bi%3A0%3Bs%3A14%3A%22_csrf-frontend%22%3Bi%3A1%3Bs%3A32%3A%22m0S1EYl99Cila8Lp16sw26GAf8yQLOYM%22%3B%7D; _identity=4ba2cce67d7e9c7cde8c8c689788411e91afd83d2a2342d5557ff9fffc4f6c54a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%22Fu17FrjnHQQBp1BM8MO7Dl1dF3hHEQM3%22%2C2592000%5D%22%3B%7D; _session=62ca34ef8bb3a54971fd5b82fe8f1f4f',
    'HTTP_ACCEPT_LANGUAGE' => 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_CACHE_CONTROL' => 'max-age=0',
    'HTTP_CONNECTION' => 'close',
    'HTTP_HOST' => '127.0.0.1:8090',
    'SCRIPT_FILENAME' => '/app/api/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => 'api.shop.d',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.12',
    'REMOTE_PORT' => '50742',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.23.1',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.0',
    'DOCUMENT_ROOT' => '/app/api/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/shop/products',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' =>
2022/10/06 15:20:24 [error] 30#30: *61 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/Request.php on line 702. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('bef" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products?accessToken=c6d3642884ec943540ffbf8c39adfe81056b63ad HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:20:24 [error] 30#30: *61 FastCGI sent in stderr: "oreAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '3a76a687-1555-48b3-b083-e2007bbf27e2',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_CONNECTION' => 'close',
  
2022/10/06 15:21:02 [error] 30#30: *63 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/Request.php on line 702. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeActio" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products?accessToken=c6d3642884ec943540ffbf8c39adfe81056b63ad HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:21:02 [error] 30#30: *63 FastCGI sent in stderr: "n', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '055b1f43-16da-40c9-aa8b-3e19c351b07a',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_CONNECTION' => 'close',
    'HTTP_
2022/10/06 15:43:46 [error] 31#31: *73 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 80. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724):" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:43:46 [error] 31#31: *73 FastCGI sent in stderr: "yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '61d7ce28-57d6-4165-bef0-61954a9ade61',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    
2022/10/06 15:45:46 [error] 31#31: *75 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 80. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('bef" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:45:46 [error] 31#31: *75 FastCGI sent in stderr: "oreAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '215459f8-7ac9-4855-84fc-eedbface5844',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_AUTHORIZATION' => 'Bearer 
2022/10/06 15:47:07 [error] 31#31: *77 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/yiisoft/yii2/web/HeaderCollection.php on line 99. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.ph" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:47:07 [error] 31#31: *77 FastCGI sent in stderr: "p(724): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '2f19f1c2-ce89-43f1-adc3-e2db007bd506',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.
2022/10/06 15:55:43 [error] 31#31: *79 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/filsh/yii2-oauth2-server/src/Server.php on line 28. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeAction', Object(yii\base\Ac" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:55:43 [error] 31#31: *79 FastCGI sent in stderr: "tionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '6f5207da-2bcb-43ee-8899-bfabcb18c595',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_AUTHORIZATION' => 'Bearer c6d3642884ec943540ffbf8c39adfe
2022/10/06 15:56:01 [error] 31#31: *81 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/filsh/yii2-oauth2-server/src/Server.php on line 28. in /app/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#4 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /app/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /app/vendor/yiisoft/yii2/filters/auth/CompositeAuth.php(57): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/filsh/yii2-oauth2-server/src/filters/auth/CompositeAuth.php(17): yii\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/ActionFilter.php(77): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))
#4 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#6 /app/vendor/yiisoft/yii2/base/Module.php(724): yii\base\Component->trigger('beforeAction', Object(yii\base\Ac" while reading upstream, client: 172.19.0.1, server: api.shop.d, request: "GET /shop/products HTTP/1.0", upstream: "fastcgi://172.19.0.8:9000", host: "127.0.0.1:8090"
2022/10/06 15:56:01 [error] 31#31: *81 FastCGI sent in stderr: "tionEvent))
#7 /app/vendor/yiisoft/yii2/base/Controller.php(166): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('shop/product/in...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/api/web/index.php(17): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_ENABLE_XDEBUG' => '0',
    'PHP_USER_ID' => '33',
    'HOSTNAME' => '7fb99c0fca3b',
    'PHP_VERSION' => '8.1.10',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'GPG_KEYS' => '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PWD' => '/app',
    'HOME' => '/var/www',
    'PHP_SHA256' => '90e7120c77ee83630e6ac928d23bc6396603d62d83a3cf5df8a450d2e3070162',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'TERM' => 'linux',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz',
    'SHLVL' => '0',
    'COMPOSER_ALLOW_SUPERUSER' => '1',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PATH' => '/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'USER' => 'www-data',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_POSTMAN_TOKEN' => '93c87eff-c049-4799-922c-edb9921beddd',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.29.2',
    'HTTP_AUTHORIZATION' => 'Bearer c6d3642884ec943540ffbf8c39adfe
